version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
     -  8000:8000
    depends_on:
      - db
  db:
    image: mysql:8.0.26

    environment:
      MYSQL_DATABASE: 'dblog'
      MYSQL_USER: 'cook'
      MYSQL_PASSWORD: '1111'
      MYSQL_ROOT_PASSWORD: '12345'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
